version: "3.8"
services:
  app:
    container_name: mainstack-backend-ts
    build: .
    ports:
      - "9030:9030"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
